# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - master
      - release/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@master
    - name: Using Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing Dependencies
      run: npm install
    - name: Building Application
      run: npm run build
    # - name: Preparing built files for uploading
    #   run: |
    #     mkdir out
    #     cp -R build out/
    #     cp -R functions out/
    #     cp firebase.json out/
    # - name: Uploading built files for deployment
    #   uses: actions/upload-artifact@master
    #   with:
    #     name: out
    #     path: out

  deploy:
      name: Deploy
      needs: build
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [12.x]

      steps:
        - uses: actions/setup-node@master
          with:
            node-version: ${{ matrix.node-version }}
        - name: Setting up Firebase
          run: npm install -g firebase-tools
        - name: Downloading files
          uses: actions/download-artifact@master
          with:
              name: out
        - name: Deploying to Firebase
          run: |
            cd out
            firebase deploy --project ${{secrets.FIREBASE_PROJECT_ID}} --token ${{secrets.FIREBASE_TOKEN}}
